steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - '--project=wow-ferronn-dev'
  - 'functions'
  - 'deploy'
  - 'gitpub'
  - '--source=https://source.developers.google.com/projects/wow-ferronn-dev/repos/github_ferronn-dev_wowdb/moveable-aliases/main/paths/gitpub'
  dir: 'gitpub'
  waitFor: ['-']
